### ISSUE TITLE
[Bug] Can't spawn fake players with /player

### ISSUE THREAD

**Issue by ninjomoe** [Gu-ZT/Curtain#144]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

curtain-mc1.20.1-1.3.2.jar

### Describe the bug - 问题描述

I use Command "/player Steve spawn", but i can't get fake players to spawn. 

![image](https://github.com/Gu-ZT/Curtain/assets/94052869/18c491e3-5831-4dac-8aff-3e2b39746d1c)

I turned my Server to offline mode and it still doesn't work

**Important note:** I host the server myself at home. I use a custom ipv4 address, generated by my wifi provider so the server address doesn't change, for that i have to write this line in my Java Arguments: -Djava.net.preferIPv4Stack=true

Here's my Serverlog:

> player steve spawn
[13:12:40 WARN]: User 8667ba71-b85a-4004-af54-457a9734eed7 - Steve doesn't have data pre-loaded, they have never been processed during pre-login in this session.
[13:12:40 ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(net.minecraft.network.protocol.Packet, net.minecraft.network.PacketSendListener)" because "this.f_8906_" is null
        Index: 1
        Listeners:
                0: HIGHEST
                1: net.minecraftforge.eventbus.EventBus$$Lambda$1521/0x0000029801767bf0@2fdbc8a3
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(net.minecraft.network.protocol.Packet, net.minecraft.network.PacketSendListener)" because "this.f_8906_" is null
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_240418_(ServerPlayer.java:1648)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_213846_(ServerPlayer.java:1643)
        at me.lucko.luckperms.forge.listeners.ForgeConnectionListener.onPlayerLoadFromFile(ForgeConnectionListener.java:126)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:262)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:254)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:318)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:298)
        at TRANSFORMER/forge@47.1.72/net.minecraftforge.event.ForgeEventFactory.firePlayerLoadingEvent(ForgeEventFactory.java:439)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:91)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11224_(PlayerList.java:420)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:178)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.createFakePlayer(EntityPlayerMPFake.java:67)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.commands.PlayerCommand.spawn(PlayerCommand.java:293)
        at MC-BOOTSTRAP/brigadier@1.20.1/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.m_242674_(Commands.java:318)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.performCommand(Commands.java:372)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:290)
        at TRANSFORMER/forge@47.1.72/org.bukkit.craftbukkit.v1_20_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:44)
        at TRANSFORMER/forge@47.1.72/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147)
        at TRANSFORMER/forge@47.1.72/org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:879)
        at TRANSFORMER/forge@47.1.72/org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:863)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_139665_(DedicatedServer.java:364)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:342)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1073)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:906)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:279)
        at java.base/java.lang.Thread.run(Thread.java:833)

[13:12:40 INFO]: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(net.minecraft.network.protocol.Packet, net.minecraft.network.PacketSendListener)" because "this.f_8906_" is null
[13:12:40 INFO]: Player steve doesn't exist and cannot spawn in online mode. Turn the server offline to spawn non-existing players

### To Reproduce - 复现问题

use command /player Steve spawn on my server

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by muqing-lt** [comment]
一样的情况，求解

**Comment by Heartfirey** [comment]
The same issue.

**Comment by patrickhoette** [comment]
Same error here, even using real player names doesn't work

**Comment by Stardito** [comment]
可能是 LuckPerms 规范了用户数据读取导致的，Curtain 获取玩家数据的方式错误，可以尝试删除 LuckPerms

It may be due to LuckPerms standardizing the reading of user data, and Curtain's method of obtaining player data is incorrect. You can try deleting LuckPerms
