### ISSUE TITLE
与luckperms冲突：/player不起作用

### ISSUE THREAD

**Issue by gujiu001** [Gu-ZT/Curtain#177]
### OS Version - 操作系统

Linux

### Version Details - 版本信息

mc1.20.1-1.3.2

### Describe the bug - 问题描述

该问题在carpet中已经修复：
https://github.com/Patbox/BoxOfPlaceholders/issues/1
https://github.com/LuckPerms/LuckPerms/issues/3104
希望尽快同步

在服务端安装curtain和luckperms后，启动服务器，/player命令无效：

[13:20:32] [警告] [minecraft/SynchedEntityData]: defineId called for: class net.minecraft.world.entity.player.Player from class tschipp.carryon.common.carry.CarryOnDataManager
[13:20:32] [警告] [luckperms/]: User cfea6145-d3e7-4d04-849a-9020b3812792 - Sleep doesn't have data pre-loaded, they have never been processed during pre-login in this session.
[13:20:32] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(net.minecraft.network.protocol.Packet, net.minecraft.network.PacketSendListener)" because "this.f_8906_" is null
        Index: 1
        Listeners:
                0: HIGHEST
                1: net.minecraftforge.eventbus.EventBus$$Lambda/0x00007f751cd17128@6b92e69e
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(net.minecraft.network.protocol.Packet, net.minecraft.network.PacketSendListener)" because "this.f_8906_" is null
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_240418_(ServerPlayer.java:1275)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_213846_(ServerPlayer.java:1270)
        at me.lucko.luckperms.forge.listeners.ForgeConnectionListener.onPlayerLoadFromFile(ForgeConnectionListener.java:126)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@47.3.1/net.minecraftforge.event.ForgeEventFactory.firePlayerLoadingEvent(ForgeEventFactory.java:412)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:58)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11224_(PlayerList.java:324)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:157)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.createFakePlayer(EntityPlayerMPFake.java:67)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.commands.PlayerCommand.spawn(PlayerCommand.java:293)
        at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.m_242674_(Commands.java:257)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.m_230957_(Commands.java:237)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_139665_(DedicatedServer.java:298)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:284)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:1583)
[13:20:32] [信息] [minecraft/MinecraftServer]: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(net.minecraft.network.protocol.Packet, net.minecraft.network.PacketSendListener)" because "this.f_8906_" is null
[13:20:32] [信息] [minecraft/MinecraftServer]: Player sleep doesn't exist and cannot spawn in online mode. Turn the server offline to spawn non-existing players

### To Reproduce - 复现问题

1.放入curtain和luckperms
2.启动服务器
3.输入/player指令
4.报错

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by YuezhangWang** [comment]
这个错误不仅仅是与luckperms冲突，而是与各种有CS sync的mod都冲突，比如Placebo、Modonomicon、Accessories、EnderIO和KubeJS等等，1.21.1在NeoForge 21.1.65与任一mod组合必现
