### ISSUE TITLE
[Bug] 服务器端假人无法自动退出游戏

### ISSUE THREAD

**Issue by xingzhiyou** [Gu-ZT/Curtain#181]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

1.3.2

### Describe the bug - 问题描述

[10:10:35 INFO]: bot_hsds lost connection: Killed
[10:10:35 ERROR]: Exception caught during firing event: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
        Index: 11
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: NORMAL
                3: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onPlayerTraveling(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: class com.aetherteam.aether.event.listeners.EntityListener onRiderTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.GlassJar collectAir(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@42676295
                7: ASM: class dev.xkmc.l2library.init.events.BaseCapabilityEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: com.mrcrayfish.framework.event.ForgeEvents@d70eb45 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@21405558
                11: ASM: dev.dubhe.curtain.events.rules.PlayerEventHandler@67a6ee2f onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: com.github.alexmodguy.alexscaves.server.event.CommonEvents@5aad65d2 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: elucent.eidolon.event.Events@ae99018 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.RottingBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.PlayerDashLeftAnimationProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.ManicBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.GriefBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.FlaskOfHealingItemInInventoryTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.DevotionBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.DashBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: class net.mcreator.mokelsbossfightsaphyra.init.ArmorAnimationFactory animatedArmors(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: com.jaquadro.minecraft.storagedrawers.core.PlayerEventListener@47da219e onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: class com.Polarice3.Goety.common.items.curios.WindyRobeItem PlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: class com.Polarice3.Goety.common.events.SoulEnergyEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: class com.Polarice3.Goety.common.events.ModEvents PlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: ASM: class com.Polarice3.Goety.common.events.LichEvents onPlayerLichdom(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                27: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@1cd912af
                28: ASM: class com.elfmcys.yesstevemodel.o0ooo0OoO0oO000Oooo000O0 o0oo000Oo000OO0O00OoOooo(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                29: ASM: class com.simibubi.create.content.equipment.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                30: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@1f15087
                31: ASM: mekanism.common.CommonPlayerTickHandler@161a6f58 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                32: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@60e729ed tickStart(Lnet/minecraftforge/event/TickEvent;)V
                33: LOW
                34: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.SynapseWingsZeta onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                35: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.SynapseWingsTheta onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                36: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.SynapseWings onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NullPointerException: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.PlayerEventHandler.onTick(PlayerEventHandler.java:27)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.__PlayerEventHandler_onTick_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
        at TRANSFORMER/forge@47.3.11/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:944)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:576)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11286_(PlayerList.java:463)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1714)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.lambda$kill$2(EntityPlayerMPFake.java:128)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1026)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:176)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1009)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1003)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:988)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:914)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286)
        at java.base/java.lang.Thread.run(Thread.java:840)

[10:10:35 ERROR]: Error executing task on Server
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:660) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.players.PlayerList.m_11286_(PlayerList.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1714) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.lambda$kill$2(EntityPlayerMPFake.java:128) ~[curtain-mc1.20.1-1.3.2.jar%23398!/:1.3.2]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1026) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:176) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1009) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1003) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:988) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:914) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
        at dev.dubhe.curtain.events.rules.PlayerEventHandler.onTick(PlayerEventHandler.java:27) ~[curtain-mc1.20.1-1.3.2.jar%23398!/:1.3.2]
        at dev.dubhe.curtain.events.rules.__PlayerEventHandler_onTick_PlayerTickEvent.invoke(.dynamic) ~[curtain-mc1.20.1-1.3.2.jar%23398!/:1.3.2]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:944) ~[forge-1.20.1-47.3.11-universal.jar%23517!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:576) ~[server-1.20.1-20230612.114412-srg.jar%23512!/:?]
        ... 16 more
[10:10:35 ERROR]: Exception caught during firing event: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
        Index: 11
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: NORMAL
                3: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onPlayerTraveling(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: class com.aetherteam.aether.event.listeners.EntityListener onRiderTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.GlassJar collectAir(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@42676295
                7: ASM: class dev.xkmc.l2library.init.events.BaseCapabilityEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: com.mrcrayfish.framework.event.ForgeEvents@d70eb45 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@21405558
                11: ASM: dev.dubhe.curtain.events.rules.PlayerEventHandler@67a6ee2f onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: com.github.alexmodguy.alexscaves.server.event.CommonEvents@5aad65d2 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: elucent.eidolon.event.Events@ae99018 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.RottingBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.PlayerDashLeftAnimationProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.ManicBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.GriefBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.FlaskOfHealingItemInInventoryTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.DevotionBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: class net.mcreator.mokelsbossfightsaphyra.procedures.DashBarPlayerTickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: class net.mcreator.mokelsbossfightsaphyra.init.ArmorAnimationFactory animatedArmors(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: com.jaquadro.minecraft.storagedrawers.core.PlayerEventListener@47da219e onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: class com.Polarice3.Goety.common.items.curios.WindyRobeItem PlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: class com.Polarice3.Goety.common.events.SoulEnergyEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: class com.Polarice3.Goety.common.events.ModEvents PlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: ASM: class com.Polarice3.Goety.common.events.LichEvents onPlayerLichdom(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                27: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@1cd912af
                28: ASM: class com.elfmcys.yesstevemodel.o0ooo0OoO0oO000Oooo000O0 o0oo000Oo000OO0O00OoOooo(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                29: ASM: class com.simibubi.create.content.equipment.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                30: net.minecraftforge.eventbus.EventBus$$Lambda$1524/0x000002908c790910@1f15087
                31: ASM: mekanism.common.CommonPlayerTickHandler@161a6f58 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                32: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@60e729ed tickStart(Lnet/minecraftforge/event/TickEvent;)V
                33: LOW
                34: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.SynapseWingsZeta onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                35: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.SynapseWingsTheta onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                36: ASM: class org.mineplugin.locusazzurro.icaruswings.common.item.SynapseWings onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NullPointerException: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.PlayerEventHandler.onTick(PlayerEventHandler.java:27)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.__PlayerEventHandler_onTick_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
        at TRANSFORMER/forge@47.3.11/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:944)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:576)
        at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.m_8119_(EntityPlayerMPFake.java:140)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:855)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:655)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:480)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:460)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1166)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1071)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286)
        at java.base/java.lang.Thread.run(Thread.java:840)

### To Reproduce - 复现问题

使用服务端mohist-1.20.1-893，Java(65.0) 21.0.4

### This issue is unique - 这个issue是唯一的

- [x] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by xingzhiyou** [comment]
报错原因是打开了  "openFakePlayerInventory": true，不确定是否是模组冲突

**Comment by xingzhiyou** [comment]
单测依然报错，不是mod冲突
[debug.log](https://github.com/user-attachments/files/17502476/debug.log)

**Comment by Au0727** [comment]
一样的问题...请问有什么解决方法吗?是关掉打开假人背包就可以了是吧,现在有什么针对这个的补丁吗?谢谢.

**Comment by xingzhiyou** [comment]
> 一样的问题...请问有什么解决方法吗?是关掉打开假人背包就可以了是吧,现在有什么针对这个的补丁吗?谢谢.

我换了原版forge端解决了，但这样就用不了插件了
